export const TOKENS = {
  color: {
    void: "var(--bg-base)",
    surface: "var(--bg-surface)",
    surfaceElevated: "var(--surface-elevated)",
    surfaceL0: "var(--bg-base)",
    surfaceL1: "var(--bg-surface)",
    surfaceL2: "var(--bg-elevated)",
    surface0: "var(--surface-0, var(--bg-base))",
    surface1: "var(--surface-1, var(--bg-surface))",
    surface2: "var(--surface-2, var(--bg-elevated))",
    surfaceL3: "var(--glass-bg)",
    surfaceL4: "var(--glass-bg-featured)",
    gold1: "var(--gold-accent)",
    gold2: "var(--gold-rich)",
    gold3: "var(--gold-deep)",
    gold4: "var(--gold-4)",
    warmWhite: "var(--text-primary)",
    textPrimary: "var(--text-primary)",
    textSecondary: "var(--text-secondary)",
    textTertiary: "var(--text-muted)",
    dim: "var(--text-secondary)",
    dimmer: "var(--text-muted)",
    success: "#5dca6e",
    successMuted: "rgba(93,202,110,0.15)",
    warning: "#e8b84a",
    warningMuted: "rgba(232,184,74,0.12)",
    danger: "#e24b4a",
    dangerMuted: "rgba(226,75,74,0.12)",
    info: "#6eb5e8",
    infoMuted: "rgba(110,181,232,0.12)",
  },
  border: {
    subtle: "var(--border-subtle)",
    default: "var(--border-default)",
    strong: "var(--border-strong)",
    spotlight: "var(--border-spotlight)",
  },
  semantic: {
    success: "#5dca6e",
    successMuted: "rgba(93,202,110,0.15)",
    warning: "#e8b84a",
    warningMuted: "rgba(232,184,74,0.12)",
    danger: "#e24b4a",
    dangerMuted: "rgba(226,75,74,0.12)",
    info: "#6eb5e8",
    infoMuted: "rgba(110,181,232,0.12)",
  },
  gradient: {
    cardDefault: "var(--glass-bg)",
    cardFeatured: "var(--glass-bg-featured)",
    heroGlow: "var(--spotlight-hero)",
    spotlightHero: "var(--spotlight-hero)",
    pageMesh: "var(--page-mesh)",
    buttonPrimary: "var(--btn-primary-bg)",
  },
  shadow: {
    card: "var(--glass-shadow)",
    cardFeatured: "var(--glass-shadow-featured)",
    button: "var(--btn-primary-shadow)",
    elevated: "var(--shadow-elevated)",
    ctaGlow: "var(--shadow-cta-glow)",
  },
  cta: {
    minHeight: "3rem",
    glow: "var(--shadow-cta-glow)",
  },
  spacing: {
    4: "0.25rem",
    8: "0.5rem",
    12: "0.75rem",
    16: "1rem",
    24: "1.5rem",
    32: "2rem",
    48: "3rem",
    64: "4rem",
    96: "6rem",
  },
  elevation: {
    flat: { background: "var(--bg-base)", border: "transparent", shadow: "none" },
    glass: {
      background: "var(--glass-bg)",
      border: "var(--glass-border)",
      shadow: "var(--glass-shadow)",
    },
    glassFeatured: {
      background: "var(--glass-bg-featured)",
      border: "var(--glass-border-featured)",
      shadow: "var(--glass-shadow-featured)",
    },
    elevated: {
      background: "var(--surface-elevated)",
      border: "var(--glass-border)",
      shadow: "var(--shadow-elevated)",
    },
  },
  focus: {
    ring: "var(--ring)",
    offset: "var(--bg-base)",
    shadow: "var(--focus-ring)",
  },
  motion: {
    durationInstant: "120ms",
    durationFast: "220ms",
    durationNormal: "400ms",
    durationSlow: "700ms",
    easeGold: "cubic-bezier(0.16, 1, 0.3, 1)",
    easeSnap: "cubic-bezier(0.34, 1.2, 0.64, 1)",
    emphasisHover: "scale(1.02)",
  },
  font: {
    arabic: "var(--font-arabic)",
    brand: "var(--font-brand)",
    mono: "var(--font-mono)",
  },
  type: {
    display: "text-5xl md:text-7xl font-bold leading-[1.05]",
    heroTitle: "text-[clamp(2.5rem,6vw,4.5rem)] font-bold leading-[1.05]",
    h1: "text-3xl md:text-4xl font-bold leading-[1.15]",
    sectionTitle: "text-3xl font-bold",
    h2: "text-2xl font-bold",
    cardTitle: "text-xl font-bold",
    h3: "text-xl font-semibold",
    body: "text-base leading-[1.65]",
    bodySm: "text-sm leading-[1.6]",
    caption: "text-sm text-text-secondary",
    mono: "font-mono tabular-nums",
  },
  viz: {
    primary: "var(--viz-primary)",
    secondary: "#6eb5e8",
    tertiary: "var(--text-secondary)",
    positive: "#5dca6e",
    negative: "#e24b4a",
    grid: "var(--grid-line)",
  },
} as const;

export type GlassElevation = 1 | 2 | 3;
export type DataDepthElevation = 2 | 3 | 4;
