import type { Campaign, Sponsor } from "@prisma/client";

export const DEMO_SPONSOR: Sponsor = {
  id: "demo-sponsor",
  name: "مطعم الشام",
  email: "demo@tenegta.com",
  password: null,
  phone: "+963900000000",
  sector: "food",
  city: "دمشق",
  address: null,
  logoUrl: null,
  verified: true,
  trustScore: 85,
  trustScoreAt: new Date(),
  currentStreak: 0,
  longestStreak: 0,
  lastActiveWeek: null,
  deletedAt: null,
};

export const DEMO_CAMPAIGN: Campaign & { sponsor: Sponsor } = {
  id: "demo-campaign",
  creatorId: "demo-creator",
  sponsorId: DEMO_SPONSOR.id,
  title: "حملة تجريبية — TENEGTA Spark",
  description: "جرّب كشف الجائزة الذهبي",
  prizeName: "وجبة مجانية",
  prizeQuantity: 50,
  prizeClaimed: 12,
  codeMode: "SHARED",
  costPerRedemption: 2,
  tier: "PRO",
  tierBoostUntil: null,
  status: "ACTIVE",
  startsAt: new Date(),
  endsAt: null,
  city: "دمشق",
  requirePhone: true,
  requireAddress: false,
  antiAbuse: true,
  heroTemplate: null,
  slug: "demo",
  promoVideoUrl: null,
  prizeImageUrl: null,
  revealStyle: "CLASSIC_GOLD",
  descriptionVariantA: null,
  descriptionVariantB: null,
  endingNotifiedAt: null,
  deletedAt: null,
  createdAt: new Date(),
  sponsor: DEMO_SPONSOR,
};
